# Generated by Django 5.0.7 on 2024-07-13 20:33

from django.db import models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_certificate_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='body',
            field=models.TextField(),
        ),
    ]
